### ISSUE TITLE
Textblock wrap value passed through as string

### ISSUE THREAD

**Issue by chapmanw** [CiscoSE/pyadaptivecards#12]
Hi

Due to changes in the system we are using Adaptive Cards for I need to set the 'wrap' value to True for a text block, however this always generates errors.

From my testing it looks like:

card=AdaptiveCard(body=TextBlock("Text",wrap=True))

Sets the value of the wrap field in the card to:

'True' rather than True, which causes the cards to fail to render.

This can be fixed by manually correcting the value:

card['content']['body'][0]['wrap']=True

However I wouldn't expect this to be normal behavour. 

Thanks
Will

**Comment by sQu4rks** [comment]
Hi @chapmanw 

thanks for raising this issue. 

Could you confirm to me which version of the library you are using? This was indeed a bug in a previous version but should be fixed in version 0.1.1 that I pushed to pypi yesterday. 

Below example shows how 0.1.1 is rendering this:

```
$ pip3 freeze | grep pyadaptivecards
pyadaptivecards==0.1.1
```

```python

from pyadaptivecards.card import AdaptiveCard
from pyadaptivecards.components import TextBlock

block = TextBlock("This is a test", wrap=True)
card = AdaptiveCard(body=[block],actions=[])
print(card.to_json(pretty=True))
```

yields this json which contains a non-string version of the boolean:

```json
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "actions": [],
    "body": [
        {
            "text": "This is a test",
            "type": "TextBlock",
            "wrap": true
        }
    ],
    "type": "AdaptiveCard",
    "version": "1.1"
}

```

**Comment by chapmanw** [comment]
Hi 

Thanks for getting back to me so quickly! Annoyingly a colleague reccomended checking for updates and I completely forgot to do it!

The good news is that I can see the wrap value is now correct. However following the upgrade cards are failing to render at the destination and are instead showing the placeholder text.

Looking at the differences between versions the only thing that stands out is that on the old version the path to the card details is under:

card['content']['body'][0]

Whereas on 0.1.1 it's:

card['content']['body']

the same data sits directly in the body. So for example getting to the 'type' value has changed from:

card['content']['body'][0]['type'] - 0.1.0
card['content']['body']['type'] - 0.1.1

Though I'm not sure this is the issue. I'll do some more testing!

Thanks again.

Will

**Comment by sQu4rks** [comment]
Hi @chapmanw 

could you provide me with an example of a card that is failing to render? If you don't want this to be displayed on a public github issue feel free to ping me on Webex Teams (or via E-mail) under mneiding (at) cisco.com.

**Comment by chapmanw** [comment]
Thanks for your help.

As you advised when definining a card:

card=AdaptiveCard(body=TextBlock("text")) would work on 0.1.0
card=AdaptiveCard(body=[TextBlock("text")])  works on 0.1.1

All working now.
