### ISSUE TITLE
OpenUrl not utilizing url attribute

### ISSUE THREAD

**Issue by Jesus-E-Rodriguez** [CiscoSE/pyadaptivecards#6]
Hi,

First of all, thank you for all the hard work you've dedicated to this. You've saved me hours of work.

The one thing I noticed was that the OpenUrl class didn't seem to be utilizing the url parameter so that when the action renders, the associated url is missing.

Adding the attribute should be able to resolve the issue:
```python
class OpenUrl(Serializable):
    def __init__(self, url, title=None,
                            iconURL=None):
        self.type = "Action.OpenUrl"
        self.title = title
        self.url = url
        self.iconURL = iconURL

        super().__init__(serializable_properties=[],
                         simple_properties=['type', 'title', 'iconURL', 'url'])
```

I might be overlooking something, but I didn't find any other way to ensure the url was rendered. Let me know if I should submit this as a pull request instead.

Thanks,

**Comment by sQu4rks** [comment]
Hi @Jesus-E-Rodriguez 

Thanks for raising this issue. 

Your proposed fix should be enough to fix this issue. If you can submit a pull request that would be perfect, thank you!

**Comment by Jesus-E-Rodriguez** [comment]
I've added the pull request, #7 thanks!

**Comment by sQu4rks** [comment]
Merged. I'll push a new release to PyPi tomorrow.
